// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
//@version=5
indicator(title='曜日の表示2',shorttitle='曜日の表示2', overlay=true, precision = 2, max_boxes_count=500, max_labels_count=500, max_lines_count=500, max_bars_back=1500) //, timeframe="", timeframe_gaps=true

// 2024/06/01 曜日表示のインジケーターを作成
// 2026/03/27 日付区切りの縦線を追加
// 2026/03/28 日足以上は曜日区切り線を非表示・月の区切り線を追加

//////////////////////////////
// 曜日の表示
//////////////////////////////
var GRP_Youbi = "==== 曜日表示 ===="
Youbi_hoursOffsetInput = '-4'
Youbi_TIMEZONE = "GMT"+Youbi_hoursOffsetInput
Youbi_exchangeOffset = hour(timenow, Youbi_TIMEZONE) - hour(timenow, syminfo.timezone)
Youbi_HOUR = hour + Youbi_exchangeOffset <= 23 ? hour + Youbi_exchangeOffset : (hour + Youbi_exchangeOffset) - 24

Youbi_resolutionInMinutes() =>
    resInMinutes = timeframe.multiplier * (timeframe.isseconds ? 1. / 60 : timeframe.isminutes ? 1. : timeframe.isdaily ? 60. * 24 : timeframe.isweekly ? 60. * 24 * 7 : timeframe.ismonthly ? 60. * 24 * 30.4375 : na)
    int(resInMinutes)
// -------------------- DAILY DIVIDERS --------------------
//tickerExchangeOffset = 5
int Youbi_dayLabelStartTime = 1

Youbi__rin = Youbi_resolutionInMinutes()

Youbi__inTimeframe = Youbi__rin <= 180 and timeframe.isintraday //timeframe.isintraday:現在の時間足が時間足（分足や秒足など）の場合には true 

Youbi_isMon() => Youbi__inTimeframe ? Youbi_HOUR == Youbi_dayLabelStartTime and minute == 0 and dayofweek == dayofweek.monday : false
Youbi_isTue() => Youbi__inTimeframe ? Youbi_HOUR == Youbi_dayLabelStartTime and minute == 0 and dayofweek == dayofweek.tuesday : false
Youbi_isWed() => Youbi__inTimeframe ? Youbi_HOUR == Youbi_dayLabelStartTime and minute == 0 and dayofweek == dayofweek.wednesday : false
Youbi_isThu() => Youbi__inTimeframe ? Youbi_HOUR == Youbi_dayLabelStartTime and minute == 0 and dayofweek == dayofweek.thursday : false
Youbi_isFri() => Youbi__inTimeframe ? Youbi_HOUR == Youbi_dayLabelStartTime and minute == 0 and dayofweek == dayofweek.friday : false
Youbi_isSat() => Youbi__inTimeframe ? Youbi_HOUR == Youbi_dayLabelStartTime and minute == 0 and dayofweek == dayofweek.saturday : false
Youbi_isSun() => Youbi__inTimeframe ? Youbi_HOUR == Youbi_dayLabelStartTime and minute == 0 and dayofweek == dayofweek.sunday : false

Youbi_dayLabelOffset = 4
Youbi__offset = Youbi__rin <= 7 ? math.round(Youbi_dayLabelOffset * 12) : Youbi__rin <= 14 ? math.round(Youbi_dayLabelOffset * 6) : Youbi__rin <= 20 ? math.round(Youbi_dayLabelOffset * 4) : Youbi__rin <= 30 ? math.round(Youbi_dayLabelOffset * 2) : Youbi__rin <= 60 ? math.round(Youbi_dayLabelOffset * 1) : math.round(Youbi_dayLabelOffset * 0.2)

Youbi_TRANSPARENT = color.new(color.white, 100)
Youbi_divider_text_color = color.blue

// Days Label
plotshape(Youbi_isMon(), text="Monday", color=Youbi_TRANSPARENT, offset=Youbi__offset, style=shape.circle, location=location.bottom, textcolor=Youbi_divider_text_color, size=size.tiny, editable=false)
plotshape(Youbi_isTue(), text="Tuesday", color=Youbi_TRANSPARENT, offset=Youbi__offset, style=shape.circle, location=location.bottom, textcolor=Youbi_divider_text_color, size=size.tiny, editable=false)
plotshape(Youbi_isWed(), text="Wednesday", color=Youbi_TRANSPARENT, offset=Youbi__offset, style=shape.circle, location=location.bottom, textcolor=Youbi_divider_text_color, size=size.tiny, editable=false)
plotshape(Youbi_isThu(), text="Thursday", color=Youbi_TRANSPARENT, offset=Youbi__offset, style=shape.circle, location=location.bottom, textcolor=Youbi_divider_text_color, size=size.tiny, editable=false)
plotshape(Youbi_isFri(), text="Friday", color=Youbi_TRANSPARENT, offset=Youbi__offset, style=shape.circle, location=location.bottom, textcolor=Youbi_divider_text_color, size=size.tiny, editable=false)
plotshape(Youbi_isSat(), text="Saturday", color=Youbi_TRANSPARENT, offset=Youbi__offset, style=shape.circle, location=location.bottom, textcolor=Youbi_divider_text_color, size=size.tiny, editable=false)
plotshape(Youbi_isSun(), text="Sunday", color=Youbi_TRANSPARENT, offset=Youbi__offset, style=shape.circle, location=location.bottom, textcolor=Youbi_divider_text_color, size=size.tiny, editable=false)


// ========== 曜日表示ここまで ================

//////////////////////////////
// 曜日区切りに縦線を表示
//////////////////////////////

//-----------------------------------------------------------------------------}
//UDT's
//-----------------------------------------------------------------------------{
type session_range
    line max
    line min

//-----------------------------------------------------------------------------}
//Methods
//-----------------------------------------------------------------------------{
n = bar_index

//Method for setting session range maximum/minimum
method set_range(session_range id)=>
    max = math.max(high, id.max.get_y2())
    min = math.min(low, id.min.get_y2())

    id.max.set_xy2(n, max)
    id.max.set_y1(max)

    id.min.set_xy2(n, min)
    id.min.set_y1(min)

//-----------------------------------------------------------------------------}
//Variables
//-----------------------------------------------------------------------------{
var chartCss = color.new(chart.fg_color, 50)
var monthChartCss = color.new(chart.fg_color, 20)

var session_range sesr = na

var line avg = na

//-----------------------------------------------------------------------------}
//New session
//-----------------------------------------------------------------------------{
dtf = timeframe.change('D')
mtf = timeframe.change('M')

//On new session
if dtf and timeframe.isintraday
    //Set delimiter
    line.new(n, high + syminfo.mintick
      , n, low - syminfo.mintick
      , color = chartCss
      , style = line.style_dashed
      , extend = extend.both)

    //Set new range
    sesr := session_range.new(
         line.new(n, high, n, high, color = chartCss)
         , line.new(n, low, n, low, color = chartCss))

//On new month
if mtf
    line.new(n, high + syminfo.mintick
         , n, low - syminfo.mintick
         , color = monthChartCss
         , style = line.style_dashed
         , width = 2
         , extend = extend.both)

